name: Lua Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: "5.1"
      continue-on-error: true
      
    - name: Fallback Lua Installation
      if: failure()
      run: |
        echo "Fallback: Installing Lua manually..."
        sudo apt-get update
        sudo apt-get install -y lua5.1 luarocks
      
    - name: Setup Luarocks
      uses: leafo/gh-actions-luarocks@v4
      
    - name: Install dependencies
      run: |
        luarocks install busted
        luarocks install luacov
        
    - name: Run tests
      run: |
        cd LibVectorMathTest
        busted --coverage
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: LibVectorMathTest/luacov.report.out
        if-no-files-found: ignore