name: Lua Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Lua
      id: lua-setup
      uses: leafo/gh-actions-lua@v11
      with:
        luaVersion: "5.1"
        luaCompileFlags: "INSTALL_TOP=./LibVectorMathTest/.lua"
        buildCache: true

    - name: Setup LuaRocks
      uses: leafo/gh-actions-luarocks@v5
      with:
        luarocksVersion: "3.11.1"

    - name: Install dependencies
      run: |
        cd LibVectorMathTest
        luarocks install busted
        luarocks install luacov
        
    - name: Run tests
      run: |
        cd LibVectorMathTest
        busted --coverage
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: LibVectorMathTest/luacov.report.out
        if-no-files-found: ignore